<template>
<div class="h-screen flex items-center justify-center">
      <div class="loadingio-spinner-dual-ball-ik06gvvhz9"><div class="ldio-zzyk0ne2j8j">
<div></div><div></div><div></div>
</div></div>
</div>

</template>

<script>
export default {

}
</script>


<style>
@keyframes ldio-zzyk0ne2j8j-o {
    0%    { opacity: 1; transform: translate(0 0) }
   49.99% { opacity: 1; transform: translate(40px,0) }
   50%    { opacity: 0; transform: translate(40px,0) }
  100%    { opacity: 0; transform: translate(0,0) }
}
@keyframes ldio-zzyk0ne2j8j {
    0% { transform: translate(0,0) }
   50% { transform: translate(40px,0) }
  100% { transform: translate(0,0) }
}
.ldio-zzyk0ne2j8j div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  top: 30px;
  left: 10px;
}
.ldio-zzyk0ne2j8j div:nth-child(1) {
  background: #1b46ba;
  animation: ldio-zzyk0ne2j8j 1s linear infinite;
  animation-delay: -0.5s;
}
.ldio-zzyk0ne2j8j div:nth-child(2) {
  background: #ab3259;
  animation: ldio-zzyk0ne2j8j 1s linear infinite;
  animation-delay: 0s;
}
.ldio-zzyk0ne2j8j div:nth-child(3) {
  background: #1b46ba;
  animation: ldio-zzyk0ne2j8j-o 1s linear infinite;
  animation-delay: -0.5s;
}
.loadingio-spinner-dual-ball-ik06gvvhz9 {
  width: 94px;
  height: 94px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-zzyk0ne2j8j {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.94);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-zzyk0ne2j8j div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>